apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: zzz
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: podinfod
          image: docker.io/siddharth67/hello-world:1.0.9 # {"$imagepolicy": "flux-system:docker-policy"}
          imagePullPolicy: IfNotPresent
