apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: minio
  namespace: flux-system
spec:
  bucketName: test-bucket-minio
  endpoint: 139.59.21.103:9000
  insecure: true
  interval: 1m0s
  provider: generic
